pipeline {
    agent { label 'Pipeline' }

    environment {
        IMAGE_NAME = "khaddy08/foodies_backend"
        CONTAINER_NAME = "foodies_backend"
    }

    stages {

        stage('Checkout') {
            steps {
                git url: 'https://github.com/KhaddyX/food-delivery-backend.git', branch: 'main'
            }
        }

        stage('Compile') {
            steps {
                bat "docker version"
            }
        }

        stage('Unit Test') {
            steps {
                bat "mvnw.cmd test"
            }
        }

        stage('Code Coverage') {
            steps {
                bat "mvnw.cmd clean verify"

                publishHTML(target: [
                    allowMissing: true,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: 'target/site/jacoco',
                    reportFiles: 'index.html',
                    reportName: 'JaCoCo Report'
                ])
            }
        }

        stage('Static Code Analysis') {
            steps {
                bat "mvnw.cmd checkstyle:checkstyle"

                publishHTML(target: [
                    allowMissing: true,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: 'target/site',
                    reportFiles: 'checkstyle.html',
                    reportName: 'Checkstyle Report'
                ])
            }
        }

        stage('Build Jar') {
            steps {
                bat "mvnw.cmd clean package -DskipTests"
            }
        }

        stage('Docker Build') {
            steps {
                bat "docker build -t foodies_backend ."
            }
        }

        stage('Docker Push') {
            steps {
                bat "docker push foodies_backend"
            }
        }

        stage('Docker Run') {
            steps {
                bat """
                docker rm -f foodies_backend || exit 0
                docker run -d -p 9090:9090 khaddy08 foodies_backend  khaddy08/foodies_backend
                """
            }
        }
    }
}